<?php

namespace Database\Seeders;

use App\Models\Account;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AccountSeeder extends Seeder
{

    public function run()
    {
         $normalMainAccount1 = Account::create([
             'name' => 'حساب عادي 1 ',
             'code' => 'n1',
             'foreign_name' => 'Normal Account 1 ',
             'card_type' => 0,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $normalMainAccount2 = Account::create([
             'name' => 'حساب عادي 2 ',
             'code' => 'n2',
             'foreign_name' => 'Normal Account 2',
             'card_type' => 0,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $normalAccount3 = Account::create([
             'name' => 'حساب عادي 3 ',
             'code' => 'n3',
             'foreign_name' => 'Normal Account 3',
             'card_type' => 0,
             'account_id' => 1,
             'result_account_id' => null,
             'final_account_id' => 12,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => true,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> true,
             'is_both'=> false,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> true,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $normalAccount4 = Account::create([
             'name' => 'حساب عادي 4 ',
             'code' => 'n4',
             'foreign_name' => 'Normal Account 4',
             'card_type' => 0,
             'account_id' => 1,
             'result_account_id' => null,
             'final_account_id' => 12,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> true,
             'is_both'=> false,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> true,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $normalAccount5 = Account::create([
             'name' => 'حساب عادي 5 ',
             'code' => 'n5',
             'foreign_name' => 'Normal Account 5',
             'card_type' => 0,
             'account_id' => 4,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => true,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $normalAccount6 = Account::create([
             'name' => 'حساب عادي 6 ',
             'code' => 'n6',
             'foreign_name' => 'Normal Account 6',
             'card_type' => 0,
             'account_id' => 2,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => true,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $normalAccount7 = Account::create([
             'name' => 'حساب عادي 7 ',
             'code' => 'n7',
             'foreign_name' => 'Normal Account 7',
             'card_type' => 0,
             'account_id' => 2,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $normalAccount8 = Account::create([
             'name' => 'حساب عادي 8 ',
             'code' => 'n8',
             'foreign_name' => 'Normal Account 8',
             'card_type' => 0,
             'account_id' => 7,
             'result_account_id' => null,
             'final_account_id' => 11,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => true,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $normalAccount9 = Account::create([
             'name' => 'حساب عادي 9 ',
             'code' => 'n9',
             'foreign_name' => 'Normal Account 9',
             'card_type' => 0,
             'account_id' => 7,
             'result_account_id' => null,
             'final_account_id' => 12,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => true,
             'is_normal' => true,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $finalMainAccount1 = Account::create([
             'name' => 'حساب ختامي 1 ',
             'code' => 'f1',
             'foreign_name' => 'Final Account 1',
             'card_type' => 3,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => true,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $finalMainAccount2 = Account::create([
             'name' => 'حساب ختامي 2 ',
             'code' => 'f2',
             'foreign_name' => 'Final Account 2',
             'card_type' => 3,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => true,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $finalAccount3 = Account::create([
             'name' => 'حساب ختامي 3 ',
             'code' => 'f3',
             'foreign_name' => 'Final Account 3',
             'card_type' => 3,
             'account_id' => null,
             'result_account_id' => 11,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => true,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $finalAccount4 = Account::create([
             'name' => 'حساب ختامي 4 ',
             'code' => 'f4',
             'foreign_name' => 'Final Account 4',
             'card_type' => 3,
             'account_id' => null,
             'result_account_id' => 12,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => true,
             'is_distributive' => false,
             'is_credit'=> false,
             'is_debit'=> false,
             'is_both'=> true,
             'is_max_limit_credit'=> false,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> true,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);
         $finalAccount5 = Account::create([
             'name' => 'حساب ختامي5 ',
             'code' => 'f5',
             'foreign_name' => 'Final Account 5',
             'card_type' => 3,
             'account_id' => null,
             'result_account_id' => 11,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => true,
             'is_distributive' => false,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [],
         ]);

         $assemblyAccount1 = Account::create([
             'name' => 'حساب تجميعي 1',
             'code' => 'a1',
             'foreign_name' => 'Assembly Account 1',
             'card_type' => 1,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => true,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [
                 ['id' => 3],
                 ['id' => 5]
             ],
             'distributive_normal_ids' => [],
         ]);

         $assemblyAccount2 = Account::create([
             'name' => 'حساب تجميعي 2',
             'code' => 'a2',
             'foreign_name' => 'Assembly Account 2',
             'card_type' => 1,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => true,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [
                 ['id' => 6],
                 ['id' => 9]
             ],
             'distributive_normal_ids' => [],
         ]);

         $assemblyAccount3 = Account::create([
             'name' => 'حساب تجميعي 3',
             'code' => 'a3',
             'foreign_name' => 'Assembly Account 3',
             'card_type' => 1,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => true,
             'is_final' => false,
             'is_distributive' => false,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [
                 ['id' => 6]
             ],
             'distributive_normal_ids' => [],
         ]);

         $distributedAccount1 = Account::create([
             'name' => 'حساب توزيعي 1 ',
             'code' => 'd1',
             'foreign_name' => 'Distributed Account 1',
             'card_type' => 2,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => true,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [
                 ['id' => 3, 'ratio' => '40%'],
                 ['id' => 5, 'ratio' => '40%'],
                 ['id' => 6, 'ratio' => '40%'],
             ],
         ]);

         $distributedAccount2 = Account::create([
             'name' => 'حساب توزيعي 2 ',
             'code' => 'd2',
             'foreign_name' => 'Distributed Account 2',
             'card_type' => 2,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => true,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [
                 ['id' => 5, 'ratio' => '40%'],
                 ['id' => 6, 'ratio' => '40%'],
             ],
         ]);

         $distributedAccount3 = Account::create([
             'name' => 'حساب توزيعي3 ',
             'code' => 'd3',
             'foreign_name' => 'Distributed Account3',
             'card_type' => 2,
             'account_id' => null,
             'result_account_id' => null,
             'final_account_id' => null,
             'currency_id' => 1,
             'parity' => 0.0,
             'ratio' => 0.0,
             'notes' => ' ',
             'is_client' => false,
             'is_normal' => false,
             'is_assembly' => false,
             'is_final' => false,
             'is_distributive' => true,
             'is_credit'=> true,
             'is_debit'=> false,
             'is_both'=> false,
             'is_max_limit_credit'=> true,
             'is_max_limit_debit'=> false,
             'is_max_limit_both'=> false,
             'assembly_normal_ids' => [],
             'distributive_normal_ids' => [
                 ['id' => 3, 'ratio' => '40%'],
                 ['id' => 8, 'ratio' => '40%'],
                 ['id' => 9, 'ratio' => '40%'],
             ],
         ]);
    }
}
