<?php

namespace Database\Seeders;

use App\Models\VoucherTemplate;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class VoucherTemplateSeeder extends Seeder
{

    public function run()
    {
        VoucherTemplate::create([
            'abbreviation' => 'vTe1',
            'name' => 'نمط السند الافتتاحي 1',
            'foreign_name' => 'voucher template entry 1',
            'voucher_type' => 0, //entry=0
            'is_entry'=>1 ,
            'is_active' =>true,
            'account_id'=> 1,
            'is_account_lock'=> 1,
            'branch_id'=> 2,
            'is_branch_lock'=> 0,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 1,
            'date'=> '2000-01-12',
            'is_date_lock'=> 1,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 1,

        ]);
        VoucherTemplate::create([
            'abbreviation' => 'vTe2',
            'name' => 'نمط السند الافتتاحي 2',
            'foreign_name' => 'voucher template entry 2',
            'voucher_type' => 0, //entry=0
            'is_entry'=>1 ,
            'is_active' =>false,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 2,
            'is_branch_lock'=> 0,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 0,
            'is_cost_center_show'=> 0,
            'date'=> '2000-01-12',
            'is_date_lock'=> 1,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry2',
            'is_accepts_distributive_accounts'=> 0,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 0,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 1,
        ]);
        VoucherTemplate::create([
            'abbreviation' => 'vTr1',
            'name' => 'نمط السند الايصال 1',
            'foreign_name' => 'voucher template receipt 1',
            'voucher_type' => 1, //receipt=1
            'is_receipt'=>1 ,
            'is_active' =>true,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 2,
            'is_branch_lock'=> 0,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 0,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 1,
            'date'=> '2000-12-02',
            'is_date_lock'=> 0,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 0,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 0,
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 0,
            'is_auto_posting_to_accounts'=> 0,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 0,
        ]);
        VoucherTemplate::create([
            'abbreviation' => 'vTr2',
            'name' => 'نمط السند الايصال 2',
            'foreign_name' => 'voucher template receipt 2',
            'voucher_type' => 1, //receipt=1
            'is_receipt'=>1 ,
            'is_active' =>false,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 4,
            'is_branch_lock'=> 0,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 0,
            'date'=> '2010-5-02',
            'is_date_lock'=> 0,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 0,
        ]);
        VoucherTemplate::create([
            'abbreviation' => 'vTr3',
            'name' => 'نمط السند الايصال 3',
            'foreign_name' => 'voucher template receipt 3',
            'voucher_type' => 1, //receipt=1
            'is_receipt'=>1 ,
            'is_active' =>true,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 1,
            'is_branch_lock'=> 1,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 1,
            'date'=> '2022-8-02',
            'is_date_lock'=> 1,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 0,
        ]);
        VoucherTemplate::create([
            'abbreviation' => 'vTp1',
            'name' => 'نمط سند الفاتورة 1',
            'foreign_name' => 'voucher template payment 1',
            'voucher_type' => 2, //payment=2
            'is_payment'=>1 ,
            'is_active' =>true,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 2,
            'is_branch_lock'=> 0,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 0,
            'date'=> '2000-9-02',
            'is_date_lock'=> 0,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 1,
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 0,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 1,
        ]);

        VoucherTemplate::create([
            'abbreviation' => 'vTd1',
            'name' => 'نمط سند اليومي 1',
            'foreign_name' => 'voucher template daily 1',
            'voucher_type' => 3, //daily=3
            'is_daily'=>1 ,
            'is_active' =>false,
            'account_id'=> 2,
            'is_account_lock'=> 1,
            'branch_id'=> 1,
            'is_branch_lock'=> 1,
            'is_branch_show'=> 1,
            'currency_id'=> 1,
            'is_currency_lock'=> 1,
            'cost_center_id'=> 1,
            'is_cost_center_lock'=> 1,
            'is_cost_center_show'=> 1,
            'date'=> '2000-02-02',
            'is_date_lock'=>1,
            'is_date_show'=> 1,
            'time'=>  Carbon::now(),
            'is_time_lock'=> 1,
            'is_time_show'=> 1,
            'notes'=> 'entry1',
            'is_accepts_distributive_accounts'=> 1,
            'is_generates_entry_for_each_item'=> 1,
            'is_auto_posting_to_accounts'=> 1,
            'is_print_duplicated_copy'=> 1,
            'is_enforce_cost_center'=> 1,
            'is_enforce_receipt_number'=> 1,
        ]);




    }
}
