<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{

    public function up()
    {
        Schema::create('bill_templates', function (Blueprint $table) {
            $table->id();
            $table->string('abbreviation')->unique();
            $table->string('name')->unique();
            $table->boolean('is_active')->default(false)->nullable();
            $table->integer('bill_type')->default(0);
            // $table->enum('bill_type', BillType::toArray())->default(BillType::sales);

            $table->string('foreign_name')->default(null)->unique()->nullable();
            $table->unsignedBigInteger('items_account_id')->default(null)->nullable();
            $table->boolean('is_items_account_lock')->default(0)->nullable();
            $table->boolean('is_items_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('discount_account_id')->default(null)->nullable();
            $table->boolean('is_discount_account_lock')->default(0)->nullable();
            $table->boolean('is_discount_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('addition_account_id')->default(null)->nullable();
            $table->boolean('is_addition_account_lock')->default(0)->nullable();
            $table->boolean('is_addition_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('cash_account_id')->default(null)->nullable();
            $table->boolean('is_cash_account_lock')->default(0)->nullable();
            $table->boolean('is_cash_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('tax_account_id')->default(null)->nullable();
            $table->boolean('is_tax_account_lock')->default(0)->nullable();
            $table->boolean('is_tax_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('cost_account_id')->default(null)->nullable();
            $table->boolean('is_cost_account_lock')->default(0)->nullable();
            $table->boolean('is_cost_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('stock_account_id')->default(null)->nullable();
            $table->boolean('is_stock_account_lock')->default(0)->nullable();
            $table->boolean('is_stock_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('gifts_account_id')->default(null)->nullable();
            $table->unsignedBigInteger('gifts_contra_account_id')->default(null)->nullable();
            $table->unsignedBigInteger('input_items_account_id')->default(null)->nullable();
            $table->boolean('is_input_items_account_lock')->default(0)->nullable();
            $table->boolean('is_input_items_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_discount_account_id')->default(null)->nullable();
            $table->boolean('is_input_discount_account_lock')->default(0)->nullable();
            $table->boolean('is_input_discount_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_addition_account_id')->default(null)->nullable();
            $table->boolean('is_input_addition_account_lock')->default(0)->nullable();
            $table->boolean('is_input_addition_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_cash_account_id')->default(null)->nullable();
            $table->boolean('is_input_cash_account_lock')->default(0)->nullable();
            $table->boolean('is_input_cash_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_tax_account_id')->default(null)->nullable();
            $table->boolean('is_input_tax_account_lock')->default(0)->nullable();
            $table->boolean('is_input_tax_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_cost_account_id')->default(null)->nullable();
            $table->boolean('is_input_cost_account_lock')->default(0)->nullable();
            $table->boolean('is_input_cost_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_stock_account_id')->default(null)->nullable();
            $table->boolean('is_input_stock_account_lock')->default(0)->nullable();
            $table->boolean('is_input_stock_account_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_gifts_account_id')->default(null)->nullable();
            $table->unsignedBigInteger('input_gifts_contra_account_id')->default(null)->nullable();
            $table->boolean('is_generate_entry')->default(0)->nullable();
            $table->boolean('is_auto_posting_to_accounts')->default(0)->nullable();
            $table->boolean('is_perpetual_inventory')->default(0)->nullable();
            $table->boolean('is_consider_gifts_from_sales')->default(0)->nullable();
            $table->boolean('is_affects_cost_price')->default(0)->nullable();
            $table->boolean('is_discounts_affects_cost_price')->default(0)->nullable();
            $table->boolean('is_additions_affects_cost_price')->default(0)->nullable();
            $table->boolean('is_auto_posting_to_stores')->default(0)->nullable();
            $table->boolean('is_use_VAT_system')->default(0)->nullable();
            $table->boolean('is_use_TTC_system')->default(0)->nullable();
            $table->boolean('is_use_sales_tax')->default(0)->nullable();
            $table->boolean('is_calculate_before_discounts')->default(0)->nullable();
            $table->boolean('is_calculate_before_additions')->default(0)->nullable();
            $table->boolean('is_apply_taxes_on_gifts')->default(0)->nullable();
            $table->boolean('is_consider_TTC_differences_as_sales_or_purchases')->default(0)->nullable();
            $table->boolean('is_addtions_affect_output')->default(0)->nullable();
            $table->boolean('is_additions_affect_input')->default(0)->nullable();
            $table->boolean('is_discounts_affect_output')->default(0)->nullable();
            $table->boolean('is_discounts_affect_input')->default(0)->nullable();
            $table->boolean('is_affects_item_profits_and_losses')->default(0)->nullable();
            $table->boolean('is_discount_affect_profits_and_losses')->default(0)->nullable();
            $table->boolean('is_addition_affect_profits_and_losses')->default(0)->nullable();
            $table->boolean('is_general_discount_is_affected_by_total_items')->default(0)->nullable();
            $table->boolean('is_general_addition_is_affected_by_total_items')->default(0)->nullable();
            $table->boolean('is_client_discount')->default(0)->nullable();
            $table->boolean('is_item_discount')->default(0)->nullable();
            $table->unsignedBigInteger('bill_price_id')->default(null)->nullable();
            $table->boolean('is_bill_price_lock')->default(0)->nullable();
            $table->boolean('is_bill_price_show')->default(0)->nullable();
            $table->unsignedBigInteger('cost_price_id')->default(null)->nullable();
            $table->boolean('is_cost_price_lock')->default(0)->nullable();
            $table->boolean('is_cost_price_show')->default(0)->nullable();
            $table->unsignedBigInteger('gifts_price_id')->default(null)->nullable();
            $table->unsignedBigInteger('branch_id')->default(null)->nullable();
            $table->boolean('is_branch_show')->default(0)->nullable();
            $table->unsignedBigInteger('cost_center_id')->default(null)->nullable();
            $table->boolean('is_cost_center_lock')->default(0)->nullable();
            $table->boolean('is_cost_center_show')->default(0)->nullable();
            $table->unsignedBigInteger('currency_id')->default(null)->nullable();
            $table->boolean('is_currency_lock')->default(0)->nullable();
            $table->boolean('is_currency_show')->default(0)->nullable();
            $table->integer('return_bill_id')->default(0)->nullable();
            $table->date('date')->default(null)->nullable();
            $table->boolean('is_date_lock')->default(0)->nullable();
            $table->boolean('is_date_show')->default(0)->nullable();
            $table->time('time')->default(null)->nullable();
            $table->boolean('is_time_show')->default(0)->nullable();
            $table->integer('payment_type')->default(0)->nullable();
            $table->boolean('is_payment_type_lock')->default(0)->nullable();
            $table->boolean('is_payment_type_show')->default(0)->nullable();
            $table->string('receipt_number')->default(null)->nullable();
            $table->boolean('is_receipt_number_show')->default(0)->nullable();
            $table->unsignedBigInteger('client_id')->default(null)->nullable();
            $table->boolean('is_client_lock')->default(0)->nullable();
            $table->boolean('is_client_show')->default(0)->nullable();
            $table->unsignedBigInteger('store_id')->default(null)->nullable();
            $table->boolean('is_store_lock')->default(0)->nullable();
            $table->boolean('is_store_show')->default(0)->nullable();
            $table->unsignedBigInteger('input_store_id')->default(null)->nullable();
            $table->boolean('is_input_store_lock')->default(0)->nullable();
            $table->boolean('is_input_store_show')->default(0)->nullable();
            $table->boolean('is_client')->default(0)->nullable();
            $table->boolean('is_cost_center')->default(0)->nullable();
            $table->boolean('is_fix_purchases_bill')->default(0)->nullable();
            $table->boolean('is_receipt_number')->default(0)->nullable();
            $table->boolean('is_fix_sales_invoice')->default(0)->nullable();
            $table->boolean('is_negative_output')->default(0)->nullable();
            $table->boolean('is_sale_less_than_cost_price')->default(0)->nullable();
            $table->boolean('is_changing_store')->default(0)->nullable();
            $table->boolean('is_changing_price')->default(0)->nullable();
            $table->boolean('is_client_has_discount')->default(0)->nullable();
            $table->boolean('is_item_is_expired')->default(0)->nullable();
            $table->boolean('is_item_has_discount')->default(0)->nullable();
            $table->boolean('is_use_payment_terms')->default(0)->nullable();
            $table->boolean('is_print_duplicated_copy')->default(0)->nullable();
            $table->boolean('is_sales')->default(0)->nullable();
            $table->boolean('is_purchases')->default(0)->nullable();
            $table->boolean('is_sales_return')->default(0)->nullable();
            $table->boolean('is_purchasing_return')->default(0)->nullable();
            $table->boolean('is_exchange')->default(0)->nullable();
            $table->boolean('is_output_store')->default(0)->nullable();
            $table->boolean('is_input_store')->default(0)->nullable();
            $table->boolean('is_beginning_inventory')->default(0)->nullable();
            $table->boolean('is_cash')->default(0)->nullable();
            $table->boolean('is_on_credit')->default(0)->nullable();
            $table->boolean('is_up')->default(0)->nullable();
            $table->boolean('is_down')->default(0)->nullable();
            $table->boolean('is_round')->default(0)->nullable();
            $table->boolean('is_none')->default(0)->nullable();
            $table->boolean('is_bill_value')->default(0)->nullable();
            $table->boolean('is_item_value')->default(0)->nullable();
            $table->boolean('is_both')->default(0)->nullable();
            $table->boolean('is_use_rounding')->default(0)->nullable();
            $table->integer('round_type')->default(0)->nullable();
            $table->integer('value')->default(0)->nullable();
            $table->integer('rounding_on_type')->default(0)->nullable();
            $table->unsignedBigInteger('rounding_account')->default(null)->nullable();


//            $table->foreign('items_account_id')->references('id')->on('accounts');
//            $table->foreign('discount_account_id')->references('id')->on('accounts');
//            $table->foreign('addition_account_id')->references('id')->on('accounts');
//            $table->foreign('cash_account_id')->references('id')->on('accounts');
//            $table->foreign('tax_account_id')->references('id')->on('accounts');
//            $table->foreign('cost_account_id')->references('id')->on('accounts');
//            $table->foreign('stock_account_id')->references('id')->on('accounts');
//            $table->foreign('gifts_account_id')->references('id')->on('accounts');
//            $table->foreign('gifts_contra_account_id')->references('id')->on('accounts');
//            $table->foreign('input_items_account_id')->references('id')->on('accounts');
//            $table->foreign('input_discount_account_id')->references('id')->on('accounts');
//            $table->foreign('input_addition_account_id')->references('id')->on('accounts');
//            $table->foreign('input_cash_account_id')->references('id')->on('accounts');
//            $table->foreign('input_tax_account_id')->references('id')->on('accounts');
//            $table->foreign('input_cost_account_id')->references('id')->on('accounts');
//            $table->foreign('input_stock_account_id')->references('id')->on('accounts');
//            $table->foreign('input_gifts_account_id')->references('id')->on('accounts');
//            $table->foreign('input_gifts_contra_account_id')->references('id')->on('accounts');
//            $table->foreign('bill_price_id')->references('id')->on('default_prices');
//            $table->foreign('cost_price_id')->references('id')->on('default_prices');
//            $table->foreign('gifts_price_id')->references('id')->on('default_prices');
//            $table->foreign('branch_id')->references('id')->on('branches');
//            $table->foreign('cost_center_id')->references('id')->on('cost_centers');
//            $table->foreign('currency_id')->references('id')->on('currencies');
////            $table->foreign('returnBill_id')->references('id')->on('');
//            $table->foreign('client_id')->references('id')->on('clients');
//            $table->foreign('store_id')->references('id')->on('stores');
//            $table->foreign('input_store_id')->references('id')->on('stores');
//            $table->foreign('rounding_account')->references('id')->on('accounts');
            $table->timestamps();
        });
    }


    public function down()
    {
        Schema::dropIfExists('bill_templates');
    }
};
